# Generated by Django 6.0.1 on 2026-01-29 00:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('tree_species', models.CharField(choices=[('pine', 'Pine'), ('cypress', 'Cypress'), ('cedar', 'Cedar'), ('eucalyptus', 'Eucalyptus'), ('mahogany', 'Mahogany'), ('oak', 'Oak'), ('teak', 'Teak'), ('other', 'Other')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Number of trees', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('average_diameter', models.DecimalField(decimal_places=2, help_text='Average diameter in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_length', models.DecimalField(decimal_places=2, help_text='Average length in feet', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Economy')], default='B', max_length=1)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_purchases', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Tree Purchase',
                'verbose_name_plural': 'Tree Purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
