"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vb*$&=mn#h@9&!ib%^v9zb_*kds9#1+yraz_@d**@vma_md=*c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]
# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/books/'
LOGOUT_REDIRECT_URL = '/login/'
# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# These settings enforce HTTPS and protect against common web vulnerabilities.
# Reference: https://docs.djangoproject.com/en/stable/topics/security/

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False prevents sensitive error information from being displayed
DEBUG = False  # Set to False in production

# ALLOWED_HOSTS prevents Host Header Injection attacks
# Only requests with these Host headers will be accepted
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.yourdomain.com']

# ============================================================================
# HTTPS/SSL ENFORCEMENT
# ============================================================================

# SECURE_SSL_REDIRECT: Redirects all HTTP requests to HTTPS
# Ensures all traffic uses encrypted connections
SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER: Trust X-Forwarded-Proto header from proxy
# Required when Django is behind a reverse proxy (Nginx, Apache, load balancer)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# ============================================================================
# HSTS (HTTP Strict Transport Security)
# ============================================================================
# HSTS tells browsers to only access the site via HTTPS
# This prevents protocol downgrade attacks and cookie hijacking

# SECURE_HSTS_SECONDS: How long browsers should remember to use HTTPS
# 31536000 seconds = 1 year (recommended minimum)
SECURE_HSTS_SECONDS = 31536000

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Apply HSTS to all subdomains
# Set to True if all subdomains also use HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Allow site to be included in browser HSTS preload lists
# Submit to: https://hstspreload.org/
SECURE_HSTS_PRELOAD = True

# ============================================================================
# SECURE COOKIE SETTINGS
# ============================================================================
# These settings ensure cookies are only sent over HTTPS connections

# SESSION_COOKIE_SECURE: Session cookies only sent over HTTPS
# Prevents session hijacking over insecure connections
SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE: CSRF tokens only sent over HTTPS
# Protects CSRF tokens from being intercepted
CSRF_COOKIE_SECURE = True

# Additional cookie security (recommended)
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to session cookie
CSRF_COOKIE_HTTPONLY = True  # Prevents JavaScript access to CSRF cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevents CSRF attacks
CSRF_COOKIE_SAMESITE = 'Strict'  # Prevents CSRF attacks

# ============================================================================
# SECURITY HEADERS
# ============================================================================
# Additional HTTP headers to protect against various attacks

# X_FRAME_OPTIONS: Prevents clickjacking by disallowing framing
# Options: 'DENY' (no framing) or 'SAMEORIGIN' (same-origin framing only)
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents MIME-sniffing attacks
# Forces browsers to respect declared content types
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Enables browser's XSS filtering
# Provides additional XSS attack protection
SECURE_BROWSER_XSS_FILTER = True

# ============================================================================
# DEPLOYMENT CHECKLIST
# ============================================================================
# Before deploying to production, ensure:
# 1. SSL/TLS certificate is installed and valid
# 2. Web server (Nginx/Apache) is configured for HTTPS
# 3. All ALLOWED_HOSTS are updated with actual domain names
# 4. SECRET_KEY is stored in environment variable
# 5. Database credentials are secured
# 6. Static files are served securely
# 7. Run: python manage.py check --deploy


# Additional cookie security (recommended)
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to session cookie
CSRF_COOKIE_HTTPONLY = True  # Prevents JavaScript access to CSRF cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevents CSRF attacks
CSRF_COOKIE_SAMESITE = 'Strict'  # Prevents CSRF attacks

# ============================================================================
# SECURITY HEADERS
# ============================================================================
# Additional HTTP headers to protect against various attacks

# X_FRAME_OPTIONS: Prevents clickjacking by disallowing framing
# Options: 'DENY' (no framing) or 'SAMEORIGIN' (same-origin framing only)
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents MIME-sniffing attacks
# Forces browsers to respect declared content types
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Enables browser's XSS filtering
# Provides additional XSS attack protection
SECURE_BROWSER_XSS_FILTER = True

# ============================================================================
# DEPLOYMENT CHECKLIST
# ============================================================================
# Before deploying to production, ensure:
# 1. SSL/TLS certificate is installed and valid
# 2. Web server (Nginx/Apache) is configured for HTTPS
# 3. All ALLOWED_HOSTS are updated with actual domain names
# 4. SECRET_KEY is stored in environment variable
# 5. Database credentials are secured
# 6. Static files are served securely
# 7. Run: python manage.py check --deploy
