# Generated by Django 6.0.1 on 2026-02-24 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Round Pole 4 inch, Dining Chair', max_length=200)),
                ('category', models.CharField(choices=[('poles', 'Round Poles'), ('offcuts', 'Off-cuts'), ('firewood', 'Firewood'), ('furniture', 'Furniture')], max_length=20)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('bundles', 'Bundles'), ('cubic_meters', 'Cubic Meters'), ('sets', 'Sets')], default='pieces', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('processing_date', models.DateField()),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_processing_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_batches', to=settings.AUTH_USER_MODEL)),
                ('tree_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_batches', to='procurement.treepurchase')),
            ],
            options={
                'verbose_name': 'Processing Batch',
                'verbose_name_plural': 'Processing Batches',
                'ordering': ['-processing_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Economy')], default='B', max_length=1)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_products', to='processing.processingbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_items', to='processing.product')),
            ],
            options={
                'verbose_name': 'Processed Product',
                'verbose_name_plural': 'Processed Products',
                'ordering': ['processing_batch', 'product'],
            },
        ),
    ]
